function ind = checkBoxesSelected(app, c)
    if c==1
        ind = [app.DataCh1CheckBox.Value*1, ...
            app.DataCh2CheckBox.Value*2, ...
            app.DataCh3CheckBox.Value*3, ...
            app.DataCh4CheckBox.Value*4, ...
            app.VoltageCheckBox.Value*5, ...
            app.TriggerCheckBox.Value*6];
        ind(ind==0) = [];
    elseif c==2
        ind = [app.DataCh1CheckBox_2.Value*1, ...
            app.DataCh2CheckBox_2.Value*2, ...
            app.DataCh3CheckBox_2.Value*3, ...
            app.DataCh4CheckBox_2.Value*4, ...
            app.VoltageCheckBox_2.Value*5, ...
            app.TriggerCheckBox_2.Value*6];
        ind(ind==0) = [];
    end
end